version: "3.8"
services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/certificates/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-public-certificates:/certificates
      - "/var/run/user/${DOCKER_UID}/docker.sock:/var/run/docker.sock:ro"
  wg-easy:
    environment:
      - WG_HOST
      - PASSWORD=${WG_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg.rule=Host(`${WG_HOST}`)
      - traefik.http.routers.wg.tls=true
      - traefik.http.routers.wg.tls.certresolver=le
      - traefik.http.routers.wg.service=wg
      - traefik.http.routers.wg.entrypoints=websecure
      - traefik.http.services.wg.loadbalancer.server.port=51821

    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - wg-easy-data:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  traefik-public-certificates:
  wg-easy-data: